name: nf-varmit
channels:
  - bioconda
  - conda-forge
dependencies:
  - samtools=1.19.2
  - bcftools=1.19
  - htslib=1.19
  - bwa=0.7.17
  - vcflib=1.0.3

  - pandas=2.1.1
  - numpy=1.26.3
  - seaborn=0.13.2
  - matplotlib-base
  - biopython=1.83

  - freebayes=1.3.6
